### PR TITLE
Update sidebar.html

### PR DESCRIPTION
**Pull request by LeslieLundquist**
probably need to change this file too for displaying Release Notes in Sidebar

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@tw15egan Please check when you can?

**Comment by tw15egan** [comment]
I'm getting an error right now, but it seems like if you add this to the bottom of the `_config.yml` it works fine:

```yaml
  releasenotes:
    output: true
    permalink: /releasenotes/:path/
```

Once this gets merged in I can take a look at the search PR

**Comment by LeslieLundquist** [comment]
Aha. Thank you. I added that. (I am learning gradually!)LESLIE D. LUNDQUIST
Director, Technical Content Development
IBM Blue Box Cloud
Phone: 1-206-607-0660
E-mail: llundquist@us.ibm.com-----TJ Egan <notifications@github.com> wrote: -----To: IBM-Blue-Box-Help/help-documentation <help-documentation@noreply.github.com>From: TJ Egan <notifications@github.com>Date: 04/05/2017 08:49AMCc: Leslie Lundquist/Seattle/IBM@IBMUS, Author <author@noreply.github.com>Subject: Re: [IBM-Blue-Box-Help/help-documentation] Update sidebar.html (#722)I'm getting an error right now, but it seems like if you add this to the bottom of the _config.yml it works fine:  releasenotes:    output: true    permalink: /releasenotes/:path/Once this gets merged in I can take a look at the search PR

**Comment by tw15egan** [comment]
👍 ✅  I was able to run this locally and the Release Notes section was correctly displayed in the sidebar.

**Pull request merged**
