### PR TITLE
Update Managing_block_storage.md

### PR DESCRIPTION
**Pull request by JillTempelmeyer**
Edits for consistency and readability. Removed some of the "marketing" messaging for this to further read as a document.

Line 24 might need another revision (I'm not familiar enough with the architecture to make this edit right now). I'd recommend removing the word "flexibility" and further clarifying the function of the scheduler for multi-backend support.

### CODE REVIEW

**Comment by JillTempelmeyer** [comment]
Perhaps we should also point to the 3.1.0 release notes (http://ibm-blue-box-help.github.io/help-documentation/gettingstarted/commontech/Customer_3.1.0_Release_Notes/) to clarify that multi-tier and multi-backend storage is supported for version 3.1.0 and up?

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer Yes, it is a good idea to point to the release notes in this version of the document.

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer I think line 24 is ok for now, if you want to get this document merged. I can go back and add some details later about which backends are supported in addition to Ceph clusters. But I need to confirm the details with engineers first. I will try to do that today.

**Comment by JillTempelmeyer** [comment]
@LeslieLundquist Sounds good, thanks. I added a link to the release notes, so I think this is ready to merge.

**Pull request merged**
