### PR TITLE
Image release notes [ver:20160607]

### PR DESCRIPTION
**Pull request by yangzhang-ibm**
Image release notes [ver:20160607]

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm I am not ready to create a new top level folder called /_cloud_images/ because it would require some top-level navigation changes so that Jekyll could work with those files and display them. Instead, I think we should actually make a "Cloud Images User Guide" under /_userguides, by renaming the existing article
https://github.com/IBM-Blue-Box-Help/help-documentation/blob/gh-pages/_commontech/Cloud_Images_Provided_by_IBM.md to be ~/_userguides/cloud_images_user_guide.md
That's because the cloud images feature has become much larger than I originally anticipated, and it really should have a user guide area, I think. Then I can make a folder for those release notes within that area, and backing files, which the user guide can link to.  I can do this work, unless you particularly wish to do it. I can also create links you requested within the release notes to the backing files. Do you approve?

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist Your suggestion sound great! I would appreciate if you can create the new folder for images user guide and add links within the release notes to the backing files. 
Btw, the backing files in that `3.0_image_patch_list` folder are always plain text files with list of packages or system updates, do you think we can keep them as .md files or it's better to convert them to .txt files or something else to avoid the restriction of .md style (e.g. if there is no blank line between lines, they will be merged to a single line). Thanks!

@nirajdp76 Do you have any suggestion for image release notes?

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm @ying-tang Actually, could you please rework this pathnames in this PR or work with Sophia to open a new PR that places these 11 files into the existing folder _userguides instead of a new _cloud_images folder? I can do the rest of the work, or Sophia can if she has time.
I prefer to keep files within the GitHub repository as .md files. What we can do to keep the backing files in .md is make them bulleted items. That way, they do not requires a space between lines, and they are still compact. But I do not mind having a space between lines if needed.

**Comment by LeslieLundquist** [comment]
@ying-tang Could you also please rename _commontech/Cloud_Images_Provided_by_IBM.md to be
_userguides/Cloud_Images_User_Guide.md? Then could you please fix the corresponding links in the 2.1.1 Release Notes to point to the new location?

**Comment by LeslieLundquist** [comment]
@ying-tang also, could you please work with @yangzhang-ibm to add links within the 3.0 cloud_images release notes that point to the backing files, section by section as appropriate? The backing files can live in a folder within the _userguides folder, that is fine.

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist: Thanks for your advice. Sure, I will update this PR to move my new files to _userguides with help from @ying-tang.

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist: I have submitted another PR #148 to rename _commontech/Cloud_Images_Provided_by_IBM.md to be
_userguides/Cloud_Images_User_Guide.md, and also fixed the corresponding links in 2.1 Release Notes to point to the new location. Please also review that one too. 
So I will keep this PR for content of 3.0 image release notes only. Thanks!

**Comment by ying-tang** [comment]
@yangzhang-ibm and I found that the backing files in sub-folder /3.0_image_patch_list do not link properly in the 3.0_Image_Release_Notes.md file. 

@LeslieLundquist  and @tw15egan the solution will require a change to the configuration file config.yml. Please consider adding these lines to config.yml:

userguides/3.0_image_patch_list:
    output: true
    permalink: /gettingstarted/userguides/3.0_image_patch_list/:path

In this way Yang's newly added files will be generated into HTML and the reference links will work.

**Comment by yangzhang-ibm** [comment]
@ying-tang: Thanks for your suggestion. 
@LeslieLundquist: Could you review and merge my PR, and then I would ask for help from you or @tw15egan to perform the changes to configurations mentioned above by @ying-tang. Thanks!

**Comment by yangzhang-ibm** [comment]
As per discussion with @nirajdp76, I will remove any association to BB release version(s) from the image release notes, so I will rename the image release notes and the folder for backing files to new names identified with dates but not BB release version.

**Comment by nirajdp76** [comment]
Do wait to get confirmation from @LeslieLundquist on next steps.

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist, please confirm whether my last comment above and the ideas in mail loop make sense, if yes, I will go update the image release notes accordingly, thanks!

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm yes, your ideas make sense so that image releases are not specifically identified with BB release versions.

**Comment by LeslieLundquist** [comment]
@ying-tang I think the backing files would display properly if they were formatted as tables. Please go ahead and reformat them. I do not want these files to be accessible from the top level of the help site, only through links from the Cloud Images release notes document, so they are always seen in the proper context. Thank you!

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist: Thanks for your confirmation. I will refine my commits in this PR and let you know once it is ready for your review again.

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist: I have already added blank lines to all the backing files, so we may don't need to use tables if the plaintext like display is also fine after we have these blank lines in .md files. btw, these backing files have hundreds of lines in total, so converting them to tables may need much effort. They will be checked as references only and won't be viewed as frequently as other docs.

**Comment by yangzhang-ibm** [comment]
@ying-tang: I have refined my changes as follows: 
1. Created a single entry page for image release notes which has links to all specific image release notes;
2. Changed the name of files and folder to use image release version (20160607) instead of BBC release version (3.0).
3. Updated the content of image release notes 20160607.
Please feel free to get my latest code from my branch "cloud_images" of my fork https://github.com/yangzhang-ibm/help-documentation, and submit a new PR with your proper adjustments to locations and formats of these files. In that case I am fine with closing my current PR and use your PR as the final one for merging into master.

**Comment by ying-tang** [comment]
@yangzhang-ibm Thanks for your prompt actions. 
I agree with you that formatting these files of hundreds of lines into tables will be labor work that makes little sense to the audience. These files are readable as they are. 

Spent quite a while debugging with local Jekyll site and had some technical difficulty in hiding the referenced specific release notes from the sidebar or the index pages.  

The files under /_userguides and its subfolder  _/image_patch_list_20160607_ are automatically converted into HTML. This is guaranteed by _config.yml configuration. But they will be by default accessible from the top level of the help site, or from the sidebar navigation.  Consulted local designer @qunqunqunqun and our thoughts are the following:
- Put these image release notes files as HTML but somwhere in the _site folder, and make it untouched when the site is regenerated. The drawback of this solution is, we have to do CSS customization for these files separately as they won't be controlled by our layout.
- Also we can make these files as static .txt files. This is the easiest way of tackling this issue, but the audience will find these files as downloads, not pages.
- The following is the best approach that we know so far. But it requires big changes to the HTML pages. So maybe TJ will be the right person to make this decision. 
  1. Add a customized "category" to the yml heading to the specific release note files.
     
     ```
      category: patch
     ```
  2. Customize the the following files with some code to exclude them from the list in index pages, which I've tested with local site: 
     
     `_gettingstarted/userguides.html`
      `gettingstarted/index.html`
     
     ```
      {% if page.title %}
        {% if page.category != 'patch' %}
                <a class="page--link" href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a>
       {% endif %}
     {% endif %}
     ```
  3. Then revise the counting mechanism in the following file to exclude these release notes, which I haven't tested. But this should work similarly. 
     
     `_includes/sidebar.html`
- There can be a similar approach using a class specified in CSS to hide these release notes. But again we will need the attribute to determine which files to hide.

@tw15egan and @LeslieLundquist may also have better solutions for this change.

**Comment by tw15egan** [comment]
I'm not sure I entirely follow what you are trying to accomplish, but the example @ying-tang shows is one way of doing this, and probably one of the quicker fixes. If you want them to simply belong in different groups on the 'Getting Started' page under User Guides, I would probably also do something similar to this. The logic would be very similar to what is done in `gettingstarted/index.html`, and would just need to be mimicked in `_gettingstarted/userguides.html`.

**Comment by LeslieLundquist** [comment]
@ying-tang @tw15egan @yangzhang-ibm Let's pursue the second option above, the easiest option, which is having the files as static .txt and downloadable only, since they are reference files. I do not wish to pursue any CSS customization or changes of that nature right now, it is too close to the release date.

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm @ying-tang The changes you made to the top level files look good. As soon as I merge this PR, the Cloud Image release notes will go live. I don't think you're ready for that until 3.0, in a couple of weeks? 

Also a small note: we won't be using the term "guest" images for IBM Blue Box Cloud. Just "Cloud Images" will be the term we use. We had a big discussion of that in the previous release. :) Ok! Thanks!

**Comment by yangzhang-ibm** [comment]
Hi @LeslieLundquist, thanks for your reminding, I have already updated the release notes in this PR to use "Cloud Images" instead of "Guest Images".

**Comment by ying-tang** [comment]
Thanks @tw15egan and @LeslieLundquist. Let's take the static file approach.

@yangzhang-ibm please make the following changes:
1. Make the specific release note topics such as centos-6.8 file as txt. Note that any yml heading should be removed. 
2. Use the following syntax in _3.0_Image_Release_Notes.md_:

```
Check [Package list](../3.0_image_patch_list/centos-6.8.txt) to see a full list of all upgraded/installed packages.
```

Note: The _.txt_ file will be displayed directly (no prompt for download) when users click on the link. If the files have other extensions, like .sh, you will be prompted to open it or save it to local.

**Comment by yangzhang-ibm** [comment]
@ying-tang Thanks for your investigation. I have submitted the changes as you suggested above, please review.

**Comment by LeslieLundquist** [comment]
Isn't it better to have the files download or prompt to open than to display .txt directly?

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm @ying-tang Are these files ready to go as downloadables? As soon as they are, I am ready to merge for 3.0. Thank you very much!

**Comment by ying-tang** [comment]
@LeslieLundquist Hi Leslie, Yang's changes look all good.
Usually txt is really safe to open so in most cases browsers  open .txt directly.  This is different from all other formats such as .sh, .exe, .yaml, etc. 
There is a little trick if we definitely want .txt to be prompted instead of opened: We could write the links in HTML code (you know this works with markdown):
`<a href="../3.0_image_patch_list/centos-6.8.txt" download>Package List</a>`
(Thanks @qunqunqunqun for the guidance).

**Comment by LeslieLundquist** [comment]
@yangzhang-ibm @ying-tang Planning to merge this on Thursday in keeping with the release date. Just letting you know.

**Comment by yangzhang-ibm** [comment]
@LeslieLundquist @ying-tang Thanks for your info!

**Pull request merged**
