### PR TITLE
Rename "Blue Box Local/Dedicated" to "Bluemix Local/Dedicated on OpenStack"

### PR DESCRIPTION
**Pull request by ying-tang**
Rename "Blue Box Local" to "Bluemix Local on OpenStack"

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@ying-tang These changes you've done look good. On the instances you haven't changed yet, I'd suggest that you just leave out the word "Cloud"  when you change the name. I don't think it is needed in those cases.

**Comment by LeslieLundquist** [comment]
@ying-tang I had hoped to see more changes on this PR today. I can't merge it while it is still inconsistent, as you know. Please let me know your plan for more edits. Thanks!

**Comment by ying-tang** [comment]
@LeslieLundquist 

HI Leslie, I thought we should separate changes for "local" from changes for "dedicated", and submit different PRs, but after a discussion with engineer folks, I believe this is not necessary. 

This would probably cause conflicts in the repository, as I will have to pull changes in this branch into another branch before doing anything there, and when committing, leave out the changes that are already included in this PR. This is error prone, and won't have any benefits. 

But the postpone leads to merge work with other pulled PRs during this period. This is a good lesson-learned. :-)

**Comment by ying-tang** [comment]
The PR should be ready and consistent now. 

I also notice some special but rare cases like "IBM Blue Box clouds" (after renaming the phrase became "IBM Bluemix on OpenStacks"). I will deal with those cases manually when this PR is merged on Monday.

**Comment by LeslieLundquist** [comment]
Hi, Sophia, I started reviewing these changes. When I got to the footer.html file, I realized I can't merge this PR at all because I already have changed that file.

Please, as I have asked you before, please DO NOT send me PRs with so many files. If there is a problem with a single file, I have to scrap the whole thing, I cannot merge it. 

I need you to break this renaming task down and make the edits folder by folder. Also, please notice the review comments I have made so far and incorporate them. Also, please do not include the HTML files in these edits, only the articles. Thank you!

**Comment by LeslieLundquist** [comment]
I have reviewed all of these diffs up to _keystone, so that is the folder where you can start working again. Please incorporate the review comments. I couldn't finish all of this review yet, so I will start again on US Monday.
Thank you for your help.

**Comment by LeslieLundquist** [comment]
Just to be clear, I did review comments on every file up to, but not including _keystone.

**Comment by ying-tang** [comment]
Hi Leslie, 
I fully understand the trouble but as explained before, separating this into several PRs was my intention but it probably would cause other problems if there is any dependency, and it couldn't totally avoid merge, but only put problems into different PRs: as this is a global change and we wait till a proper day, before this PR gets pulled in, any other change overnight will cause merge. 

"Cannot merge" means we need to manually merge. This is a very boring task, I fully understand. I had managed to merge for a "contaminated" branch on my local and it took me one day. 

Regarding the .md files, it would take much time for me to separate this PR by folder. From my point of view this would make little sense.. kind of labor work. 

Anyway, I am trying to do this ... Let's try to find a better approach next time. For example, as you have permission to change the master branch, you could run the command line to "globally replace" in one PR after we have everything else done. In this way, we may not need any merge. What do you think?

**Comment by ying-tang** [comment]
Closing this PR.

**Comment by LeslieLundquist** [comment]
Hi, Sophia, I think that in your new PRs you did not include the specific, line-by-line review comments that I gave in this PR. Those need to be included in the new PRs before I can merge anything. Thanks!

**Pull request closed without merging**
