### PR TITLE
Minor editorial changes; Imported concept description from ICOS

### PR DESCRIPTION
**Pull request by ying-tang**
Minor editorial changes; Imported a concept description from ICOS.

### CODE REVIEW

**Comment by ying-tang** [comment]
We notice that Ephemeral is explained here under [Glance](http://ibm-blue-box-help.github.io/help-documentation/glance/disk-capacity-constraints/), but Object Storage is seldom mentioned in Blue Box help documentation. It's different, especially that it might be only accessed using APIs.

Ideally we hope to have a similar comparison table about Ephemeral, Block Storage and Object Storage as [ICOS reference](http://open.ibmcloud.com/documentation/managing-and-monitoring-storage-resources.html) to tell customers their differences. But not sure where to put this table.

**Comment by LeslieLundquist** [comment]
This table in the ICOS reference looks perfect, just the part at the top under Basic concepts and the part under that, explaining OpenStack storage concepts. It is the type of conceptual documentation our help site needs, exactly! We need more concept explanations like this. Good call, Sophia! 

You could import these tables into a new article. Then we could link to it from several of the articles about storage. Maybe you could call the new article "OpenStack Storage Concepts" or something similar to that. We could put it under the OpenStack folder, under User Documentation. Does that seem reasonable?

**Comment by LeslieLundquist** [comment]
P.S. I think that Blue Box did not offer object storage for a long time, it is more recent. So that is why the documentation is sparse. We can fix that! Do you have a document about Object Storage, specifically?

**Comment by LeslieLundquist** [comment]
@ying-tang this is ready to merge, I just want to be sure you can see these comments first. Good work!

**Comment by ying-tang** [comment]
@LeslieLundquist Good point! I've created another PR（PR#108) for the newly added topic "OpenStack storage concepts" under _openstack. Please pull both after review. Let's keep on adding more concepts to help users understand the background.

**Comment by ying-tang** [comment]
ICOS has some object storage topics but existing topics concern interactions with SoftLayer.  For example, they talk about how to back up ICOS object storage to SoftLayer (using swift and duplicity). Although the steps may be correct, I cannot see now a business reason to emphasize this for Blue Box. Let's think about it. 
The two topics are: [Using SoftLayer Object Storage to backup or transfer data in IBM Cloud OpenStack Services](http://open.ibmcloud.com/documentation/backup-using-object-storage.html) and [Backing up your volumes to SoftLayer Object Storage using duplicity in Linux](http://open.ibmcloud.com/documentation/backup-using-duplicity.html).

**Comment by LeslieLundquist** [comment]
You are right, we definitely do not want to emphasize  interactions with SoftLayer for Blue Box. I think most of these interactions will have changed in details, anyway.

**Comment by LeslieLundquist** [comment]
You are right, we definitely do not want to emphasize  interactions with SoftLayer for Blue Box. I think most of these interactions will have changed in details, anyway. For the articles you've linked: these services are not available to Blue Box clients, because it would put Blue Box in competition with SoftLayer's legacy clients, as far as I know. Blue Box has other options. These documents should not be transferred.

**Comment by ying-tang** [comment]
@LeslieLundquist  This PR may be pulled only after #108 is available. We have added a reference link to that new topic. Please verify.

**Comment by ying-tang** [comment]
This is now safe to pull.

**Pull request merged**
