### PR TITLE
Fix missing figure issues and misplaced code blocks

### PR DESCRIPTION
**Pull request by ying-tang**
Add the %hightlight% tags for proper line break in code blocks
Correct the image URLs

### CODE REVIEW

**Comment by ying-tang** [comment]
@LeslieLundquist It seems that the multiple-line code blocks do not have an exact preview when we look at the source code. For example, 

{% highlight bash %}

# nova hypervisor-stats

...

# nova hypervisor-stats

{% endhighlight %}

This looks bad in preview but actually the output in http://ibm-blue-box-help.github.io/help-documentation/ pages will be fine. And it is more tricky if we add indents (for bullets and ordered lists). Do you have any suggestions about this?

**Comment by LeslieLundquist** [comment]
Yes, you are right, the code blocks do not show up correctly until Jekyll processes them, so it is hard to pre-view them. This {% highlight bash %} tag is intended only for blocks of code of three lines or more. I do not think there should be any headers or bulleted lists within a code block.

What I have done is to leave out the {% highlight bash %} and {% endhighlight %} tags, so that I can see the document almost as it will look, to see how the code looks. Then I add them at the very last thing before I make a PR.

Also, what Jesse Proudman says is that code lines should be short so they do not need to wrap, if possible. "Code should not wrap," is his direct quote.  So avoid it as much as possible. If you need to get help, an engineer could probably show you where a code line could be split. In a very few cases, the line cannot be split, and that is when to use {% highlight bash %} tags.

Does that make sense to you?

**Comment by LeslieLundquist** [comment]
Oh! I see what happened above, you must have had a '# ' character the beginning of the line, and markdown reads that as a first level header tag. In code, of course, that is a comment. Check with an engineer for the specific case, but usually you can delete the '#' because this code would be executing, not commented out.

**Comment by ying-tang** [comment]
Thanks Leslie for your patience. So our guidelines will be:
1. Try our best not to wrap code lines. Make the code line short and ideally single-line. 
2. If the code snippet has more than 3 lines, we will use {%highlight%} tags.
3. If {%highlight%} tags are used, preview with ordinary code block tags and make sure everything looks fine. 

What I was really uncertain about is the indent of code blocks within ordered or unordered lists. For example:
1. Do something
2. Do something
    {% highlight bash %}
    some code
   {%endhighlight%}
3. Do something else
Most code blocks in existing Blue Box help topics do not indent. So I will do preview without the {%highlight%} tags and make sure the sequence 1,2,3.... does not get disturbed.

**Comment by LeslieLundquist** [comment]
Yes, I have worked to have the code blocks not indent, because they are difficult for anyone to cut and paste when they are indented.  Also, if we indent, we would need to be scrupulous to observe the indentation conventions that the engineers use when writing code or scripts. Even the tiniest misplaced space character is a disaster for their scripts. That is why I have avoided it so far, just easier.

**Comment by ying-tang** [comment]
Made some further changes to remove indents from code blocks whenever possible. For ordered lists, I tend to keep the tabs. Verified that this won't case extra space in code when copy/paste. The markdown will indent the "block" but not in front of the code. 

Please pull this request. The figures have been missing with broken links for a while, which is a bad experience for audience. If further issues are detected, we could fix after that.

**Pull request merged**
