### PR TITLE
Use CLI to create volumes with two different Ceph types

### PR DESCRIPTION
**Pull request by ying-tang**
Use CLI to create volumes with two different Ceph types

### CODE REVIEW

**Comment by ying-tang** [comment]
Again this is about the Ceph feature for R3.1.0. This might be pulled later near our release.

**Comment by knandya** [comment]
Is this going to be part of customer facing documentation? An end-user will not have an option to create a cinder volume type
cc: @nirajdp76

**Comment by LeslieLundquist** [comment]
Good question! Maybe this doc was meant to be submitted to the other repo?

**Comment by knandya** [comment]
I've to take my comment back.
 This PR is about creating actual cinder volumes with a given type . It is not about creating a cinder volume type. Sorry for the confusion. 

Deleted my original comment.

**Comment by LeslieLundquist** [comment]
Ha ha ha! Thank you!

**Pull request merged**
