### PR TITLE
Text in Horizon topic was missing

### PR DESCRIPTION
**Pull request by ying-tang**
Text in Horizon topic was missing

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@ying-tang It is much easier for me to review (and I can be quicker) if you limit the number of files changed per PR to one, maybe two at the most. Ha ha ha! Thanks for this sweeping update.

**Comment by LeslieLundquist** [comment]
How did you even get 192 commits? That is awesome, for a one line change. I am still laughing out loud.

**Comment by ying-tang** [comment]
Hi Leslie, sorry about the inconvenience. 

The intention was to get one single commit for a PR, as suggested by an engineer folk. And I am trying to do without GitHub Desktop: command line only. 

It seems that the problem lies in my local master branch -  any newly created branch is duplicated from this. My local branch used to keep in sync with IBM-Blue-Box-Help/gh-pages with GitHub Desktop and each sync turned out to be a commit.

**Comment by LeslieLundquist** [comment]
@ying-tang Yes, I think I understand why it works that way and ends up looking so complicated, when you make several commits to your local master branch. 

I was wondering why you've decided to stick only with the command line? For sure it is cool and powerful. I just find that the graphical interface is easier for most things. I only use the command line for big stuff like the rename. You might try both. I do not use the Desktop app, but the interface within GitHub itself. 

Anyway, no matter what you choose, I really appreciate your attention to detail! Keep up the good work!

**Comment by ying-tang** [comment]
@LeslieLundquist  Hi Leslie, thank you for your understanding! 

Just to stand on the "strict" side. My colleague kindly reminded me that, engineers who produce code, would not tolerate the code history with a long list of personal merge commits. This would make the history look "unclean".  

Truly we know that we don't have to worry too much about the documentation history. So it's just a good practice to use command line to keep a PR with one commit.  

With Desktop, it is unlikely to have a "clean" commit as each sync with cause a commit in local. 
But command line, web UI, and Desktop are all good and powerful tools.

**Pull request merged**
