### PR TITLE
Add an illustration for multi-tier network

### PR DESCRIPTION
**Pull request by ying-tang**
Add an illustration for multi-tier network

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@ying-tang This looks really nice! Could you please add another router, the "main router" at the top of the hierarchy, and have each child router talk to the main router and talk externally. They do not actually communicate with each other as seems to be indicated here--instead, these 2 networks are isolated from each other.

**Comment by ying-tang** [comment]
@LeslieLundquist Hi Leslie, from the neutron code block my understanding is a little different: 
1. Only test1 network is directly connected to external (`neutron router-gateway-set test-router1 external`) and test2 is connected to external through test1. 
2.  The next hop of test2 network is the gateway of test1 (`neutron router-update test-router2 --routes type=dict list=true destination=0.0.0.0/0,nexthop=162.16.0.1`) . 

This implies that test2 is treated as the child network of test1, so that it is isolated from external network. And this is also why this is called "multi-tier router". 

Uploading the updated figure. Feel free to further discuss.

**Comment by LeslieLundquist** [comment]
@ying-tang This situation is a special case. Seriously, I have just confirmed with Chris Wheeler that, as I said previously, each child router, test1 and test2, talks to the main router, and also to the external internet, but they do not talk to each other. This situation is created to isolate the test1 subnet from the test2 subnet. This is to set up 2 separate subnets within a single project. This is the architecture that needs to be depicted. Thank you!

**Comment by ying-tang** [comment]
@LeslieLundquist  Now I guess both you and Chris' understanding are actually the same as ours. The problem lies in the difference between the description and the sample code. 

If we do not give any sample code block, a picture with a main router and two subnets, with whatever names, are certainly correct. 

In the code block, test-router1 is in fact the "main router". The test1 subnet is the "parent" subnet, not one of the child subnets. You could observe from the neutron commands and the test results that, traffic outbound from test2 subnet goes through the test1 gateway. For example, in the code comments "Set default route on child router to test1 subnet gateway address". 

To match the description better we may add a subnet test3, which is also a child subnet of test1 and isolated from test2. 

Would suggest again that we add some descriptions about the IDs to help readers understand, such as `b490f691-364f-4f7c-866c-1c45e7b8f8cf`, at least telling users whose ID this is.

**Comment by LeslieLundquist** [comment]
@ying-tang I am rewriting the code. Changing the names to be more descriptive and adding a third router/network.

**Comment by LeslieLundquist** [comment]
@ying-tang and the drawing still looks very nice! Sorry you will need to do it again. Hopefully this will be the last time.

**Comment by ying-tang** [comment]
It's quite easy to update the figure. No worries.

**Comment by LeslieLundquist** [comment]
@ying-tang I updated the code to reflect the desired configuration. Now you can make the drawing for the new document. Thanks!

**Comment by LeslieLundquist** [comment]
@ying-tang if you just update the image at _img/multi_router_network.png, I have already put your link to the image into the updated file.

**Comment by LeslieLundquist** [comment]
@ying-tang Closing this PR so you can work with the new file.

**Pull request closed without merging**
