### PR TITLE
Fix image download example curl command.

### PR DESCRIPTION
**Pull request by nirajdp76**

### CODE REVIEW

**Comment by dlundquist** [comment]
Do we really want the `-i` and `-k` flags? Do we need to include the HTTP headers? Recommending to disable TLS certificate validation isn't a good practice.

**Comment by LeslieLundquist** [comment]
Waiting for resolution of Dustin's comment before merge.

**Comment by nirajdp76** [comment]
I have addressed Dustin comment and squashed the commits.

**Comment by dlundquist** [comment]
@nirajdp76 Looks much better, thanks for resolving this.

**Pull request merged**
