### PR TITLE
Updated links to work with new formatting

### PR DESCRIPTION
**Pull request by JillTempelmeyer**

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
I think the links still are incorrect. I believe they need to include /_gettingstarted/_commontech/  in the path, not just /_commontech/. Could you try going to the top level splash page of the customer docs, and clicking in to the release notes, just to doublecheck the full path?

**Comment by LeslieLundquist** [comment]
Here:
http://ibm-blue-box-help.github.io/help-documentation/gettingstarted/commontech/release_notes_for_customers/

**Comment by LeslieLundquist** [comment]
In fact they do not need the underscores but both subdirectories must be specified.

**Comment by tw15egan** [comment]
These links are pointed at the internal github repo, which is probably not what we want to send our users to 😀  Instead, make sure the url is starting with `ibm-blue-box-help.github.io` and does not contain `blob`. An easy way to make sure you've got it right is to just go to the current document on the live site, and copy that URL. To link to a different part of that page, just put a `#` and then the heading that you want to target. And make sure you convert spaces to dashes. Let me know if you have any questions and I can help out! 

This is what the link should look like when your done!

`[Additional types of Expansion Compute Nodes are available.](http://ibm-blue-box-help.github.io/help-documentation/gettingstarted/commontech/release_notes_for_customers/#optional-expansion-compute-nodes-now-available)`

**Comment by LeslieLundquist** [comment]
Thanks, TJ, Jill is learning about all of this. I am distracted with other work and trying to help her figure it out. I love that you are paying attention to us!!

**Comment by tw15egan** [comment]
Yup no worries, it's a complicated thing to jump right into so I'm just trying to offer some clarification as to how it all works. Jill, are you by any chance on the Cloud Platform slack?

**Comment by JillTempelmeyer** [comment]
So sorry-- Thank you, TJ and Leslie, for your help and clarification!! TJ, I'm on the cis-dev Slack channel, but can't log into the Cloud Platform channel. Regardless, I'd love your help! Are you able to add me?

**Comment by tw15egan** [comment]
@JillTempelmeyer No need to be sorry, I didn't include this information in my documentation 😱

But yeah, I can get you added. Go to [cloudplatform.slack.com](cloudplatform.slack.com) and enter a business justification aka you need to work with me regarding an IBM Cloud product offerings Help Documentation. It should only take 30 minutes to get approved, and then you'll be good to go and we can go from there

screen shot 2016-05-03 at 6 42 22 pm

**Comment by LeslieLundquist** [comment]
This is great, people. Please keep me in the loop on your work and collaboration.

**Comment by tw15egan** [comment]
@LeslieLundquist Once Jill gets the authorization to join the Cloud Platform Slack, we can create a private message thread for Blue Box Help related conversation so we can resolve issues and learn from each other

**Comment by JillTempelmeyer** [comment]
Yes, creating a private message thread would be awesome! 
On a side note: I really promise I am as good at reading documentation as I am at writing it... but I don't see an option to enter a justification. I'm only seeing the image below, which won't let me log in with my w3 ID :(

screen shot 2016-05-03 at 6 58 40 pm

**Comment by tw15egan** [comment]
@JillTempelmeyer [Maybe this link?](https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/W0b18f57537fa_4d83_be88_7e9aaffed4f8/page/Requesting%20access%20to%20CloudPlatform%20Slack)

**Comment by JillTempelmeyer** [comment]
Awesome - that link worked! I've requested access and will let you know once it's approved. Thanks for your help!!

**Comment by LeslieLundquist** [comment]
Very well done, correct URLs. These changes were covered in other pull requests. Awesome work, though.

**Pull request closed without merging**
