### PR TITLE
Pull together thoughts and start to draft RHOSP topics

### PR DESCRIPTION
**Pull request by ying-tang**
Pull together thoughts and start to draft RHOSP topics

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@ying-tang @JillTempelmeyer Nice work, Sophia! I will double check with the engineers because we might also be moving Bluemix Private Cloud to the Newton release of OpenStack. At least it has been discussed. Sangeetha has been reviewing the Newton release notes.

**Comment by LeslieLundquist** [comment]
@ying-tang @JillTempelmeyer I'd like to find a place somewhere in our docs (maybe not even in this overview) that we can link specifically to these network tuning techniques, a section within the Red Hat networking documentation: 
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Tuning_and_Optimization_Guide/sect-Virtualization_Tuning_Optimization_Guide-Networking-Techniques.html

Your ideas are greatly appreciated!

**Comment by ying-tang** [comment]
Agree with you that the topic [Improving Cloud Performance](http://ibm-blue-box-help.github.io/help-documentation/gettingstarted/userguides/Improving_Cloud_Performance/) is the best place to put this link.

**Comment by LeslieLundquist** [comment]
merging to _drafts and I will fix a few typos I noticed

**Pull request merged**
