### PR TITLE
Import one topic from ICOS about multiple ephemeral

### PR DESCRIPTION
**Pull request by ying-tang**
Import one topic from ICOS about multiple ephemeral

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
Like "Horizon," the word "Nova" should be capitalized when it appears in text, because it is the name of an OpenStack project. In code, it should not be capitalized (which is correct already in this doc.) Thanks!

**Comment by LeslieLundquist** [comment]
@ying-tang One of our senior network engineers has commented that this practice might be deprecated, or at least it is uncommon. Is it something that would have a specific use case? If so, let's frame up this document with that use case, not just because it is possible. I think that approach would be more helpful for a customer facing doc.

**Comment by ying-tang** [comment]
Thanks Leslie.

 Also consulted with dev and testers, and they believe with 3.0 we encourage users to use OpenStack client, instead of the separate nova/neutron/glance/...clients, although separate clients are still used internally. If this true, this topic certainly makes no sense. Also, we might need a global check on other command line examples. 

Keep this PR open temporarily in case we have more discussions. @maohuang, @yangzhang-ibm

**Comment by LeslieLundquist** [comment]
@ying-tang This document definitely is calling upon the Nova client, not the OpenStack client. Also, jlk tells me he does not know a way to use the OpenStack client (directly) to create multiple ephemeral. So perhaps this document does not make sense as it is. I do like the idea of framing it with a use case, if we can come up with one.
I just wonder whether this use case might apply to PureApp, since their storage is only ephemeral? Could you check with your engineers there?
Or we might change the title of the article to something general like "Launching an Instance Using the Nova Command Line Interface" and not emphasize the ephemeral storage aspect.

**Comment by ying-tang** [comment]
@LeslieLundquist In the current integration with PureApp we don't involve any storage, but will in the near future. So maybe it's better choice now to take the second approach.

**Comment by ying-tang** [comment]
@LeslieLundquist  please review the pull in the request.

**Comment by LeslieLundquist** [comment]
@ying-tang I am waiting on this to hear back from an engineer, ok? That's why I haven't merged it yet.

**Comment by ying-tang** [comment]
@LeslieLundquist  Sure, of course.

**Pull request merged**
