### PR TITLE
Import one topic from ICOS: Using Horizon to launch an instance

### PR DESCRIPTION
**Pull request by ying-tang**
Import one topic from ICOS: Using Horizon to launch an instance.

### CODE REVIEW

**Comment by ying-tang** [comment]
This is a Horizon topic imported from ICOS. Also verified its accuracy against the corresponding [OpenStack Docs](http://docs.openstack.org/user-guide/dashboard_launch_instances.html#launch-an-instance). 

The topic may have duplicate information as "Cloud Images provided by IBM" under getstarted/commontech. But I believe it makes more sense to have the information with this topic, since "Cloud Images provided by IBM" is supposed to talk about customer image operations. We could remove duplicate information from there and add reference links. 

Maybe this topic will need some more snapshots.

**Comment by LeslieLundquist** [comment]
@ying-tang Good work. Here's a comment from JLK, though:

"This document will have to change with the 3.0.0 release as the boot instance UX in Horizon has changed in Mitaka."

So, I can merge it and then you can look into updating it right away in the next two weeks, or we could put it into drafts and give you time to do 3.0.0 updates first. Which would you prefer?

**Comment by ying-tang** [comment]
Hi Lesile, Thanks for catching this issue. Even the OpenStack docs fall behind. 

This is a noticeable change in 3.0 so I guess we will need to fix this in two weeks. I've got part of the snapshots today. Will keep working on this.

**Comment by LeslieLundquist** [comment]
@ying-tang This file is looking good. Nice work so far. What else is needed?

**Comment by ying-tang** [comment]
@LeslieLundquist We are not pending on anything at this moment after local nova dev provided comments. But more review&comments are very welcome. Maybe we can pull this in and wait for further comments.This is for release 3.0.

**Comment by LeslieLundquist** [comment]
@omgjlk@us.ibm.com  Could you please take a look at this doc for us?

**Comment by LeslieLundquist** [comment]
@ying-tang In line 126, a correction is needed. There is not anything we call the IBM Blue Box OpenStack Dashboard. We would just call it the Horizon dashboard.

**Comment by LeslieLundquist** [comment]
@ying-tang sorry, it was line 128. See in lines below that, you refer to the IBM Blue Box Horizon dashboard.  Let's use that terminology.

**Pull request merged**
