### PR TITLE
Upgrade python-opnestackclient

### PR DESCRIPTION
**Pull request by narengan**

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@narengan I had been told that using sudo su to install pip is not a recommended method. This file has that info: http://ibm-blue-box-help.github.io/help-documentation/openstack/api/openstack-api-getting-started/

I am just needing to verify with you that installing python-openstackclient with sudo su is not as dangerous?

**Comment by narengan** [comment]
I think this needs sudo permissions. In this scenario we are upgrading the client on the linux box and not mac.

**Comment by LeslieLundquist** [comment]
@narengan Ok, thanks for that info! Is it ready to merge? (I noticed the WIP)

**Comment by narengan** [comment]
@LeslieLundquist looks good now :)

**Pull request merged**
