### PR TITLE
Remove the duplicate topic

### PR DESCRIPTION
**Pull request by ying-tang**
Remove the duplicate topic. This should be under cinder only.

### CODE REVIEW

**Comment by ying-tang** [comment]
Was about to import ICOS [reading the usage metrics](http://open.ibmcloud.com/documentation/read_usage_metrics.html) topic. Consulted engineers and found that  customers are not encouraged to use Ceilometer in Blue Box.  Ceilometer, in more occasions, is used "internally" by Heat. So the import makes little sense. 
So if this is true, we may hide "Ceilometer" category from the homepage.

**Comment by LeslieLundquist** [comment]
There is also a design issue if we hide Ceilometer. I would have to consider it carefully. Let me think about it.

**Comment by LeslieLundquist** [comment]
Also, there is a duplicate article because GitHub will not keep an empty folder. I have been aware that there is a duplicate. Originally, there were going to be additional articles submitted by CSM, which is why it was in the design, as 2.0  initially incorporated Ceilometer. Again, I am still thinking about this issue.

**Comment by LeslieLundquist** [comment]
Just learned there is some Ceilometer stuff coming in 3.0.

**Comment by ying-tang** [comment]
Sure. In this case, I would close this PR for now. Let's create new PRs with meaningful subjects after we get the input about Ceilometer.

**Pull request closed without merging**
