### PR TITLE
Limitation about file injection with nova boot (tested in 3.0)

### PR DESCRIPTION
**Pull request by ying-tang**
Limitation about file injection with nova boot (tested in 3.0). There is an email thread discussiong this. Will also invove dev/test to confirm.

### CODE REVIEW

**Comment by ying-tang** [comment]
Inviting @maohuang and @omgjlk@us.ibm.com to review and comment.

**Comment by ying-tang** [comment]
Also @nirajdp76

**Comment by LeslieLundquist** [comment]
@ying-tang @nirajdp76 @omgjlk@us.ibm.com I have not seen the email thread on this, Sophia could you forward it? Also, this information might actually belong in release notes, if it is a limitation.

**Comment by LeslieLundquist** [comment]
@nirajdp76 Is the use case listed in this article : http://docs.openstack.org/user-guide/cli_config_drive.html
the one we are interested in for this feature? Why do we call it file injection?

**Comment by ying-tang** [comment]
@LeslieLundquist From my understanding, this feature is called "file injection" because it uploads a local file onto the newly booted server, something like "injection". This is also official wording in OpenStack, for example, http://docs.openstack.org/admin-guide/cli_set_compute_quotas.html.

**Comment by LeslieLundquist** [comment]
@ying-tang  Ok, thank you! I see what you mean.

**Comment by LeslieLundquist** [comment]
@ying-tang Could you also please add the link to http://docs.openstack.org/admin-guide/cli_set_compute_quotas.html. with the note that the customer can find more information about injected files and quotas in that document. Also, can you tell me specifically how the user experience is improved because this value is set to "false'? Are there faster loading or booting times, for example? I think the wording there is too vague to be helpful to the customer. Thanks!!

**Comment by ying-tang** [comment]
@maohuang How about we change the statement like this:

In IBM Blue Box Release 3.0, this feature is by default **not enabled**: The `force_config_drive` parameter in the `nova.conf` file is set to `false`. This is because support of this feature depends on the image from which the new instance is booted. Some of the customer images may not support this option. 

If you want to inject files while booting an instance, you can pass the `--config-drive true` option to the `nova boot` command to enable this feature. For example,

```
nova boot --image <image_name> --flavor <flavor> --nic <net-id=net_uuid> --security-group <security_group> --key-name <key_name> --file <dst_path=src_path> --config-drive true <instance_name>
```

For more information about the injected files and quotas, see [Manage Compute service quotas](http://docs.openstack.org/admin-guide/cli_set_compute_quotas.html). 
For more information about the `nova boot` command, see [Compute command-line client reference](http://docs.openstack.org/cli-reference/nova.html).

Please also invite Jesse to review this topic. Thanks.

**Comment by LeslieLundquist** [comment]
This Looks good to me. +1

**Pull request merged**
