### PR TITLE
Update Box_Panel.md

### PR DESCRIPTION
**Pull request by JillTempelmeyer**
Now that I have access to Public Box Panel, I can't seem to access Lock Box (I get an error page when trying to access my Lock Box messages). Please note that I have not yet been able to walk through all of the steps that require `cloud_admin` credentials.

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
That's because you don't have cloud-admin credentials at this time. I am not sure what is up with Lockbox, though.

**Comment by LeslieLundquist** [comment]
I see the changes you wish to make. I like the information updates you've done, but I'm going to have to enter them manually into the _other_ pull request, which I entered and still is open, for the BPUG, because it will create a merge conflict anyway. I can do that.

**Comment by JillTempelmeyer** [comment]
Thanks, Leslie, for your help (and patience). Just sent you an email re: how to avoid preventing merge conflicts in the future.

**Comment by LeslieLundquist** [comment]
Consolidated these changes into PR #40

**Pull request closed without merging**
