### PR TITLE
Update BYOFIP_support.md

### PR DESCRIPTION
**Pull request by LeslieLundquist**
edited for style and grammar

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer here is a draft with my edits. Was this what you had in mind?

**Comment by JillTempelmeyer** [comment]
@LeslieLundquist I was thinking less about style/grammar edits, and more about this needing to be more descriptive. Particularly, the "Connecting to a Guest VM" steps in their current form seem like they could be difficult for a customer to follow. What do you think?

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer Yes, some customers will know how to do these steps, some would have a lot of trouble. I think the engineer did not include more information because the process would be different for Horizon or CLI. I think we should pick one and illustrate the steps. I think most customers could relate to the steps in Horizon.

@ying-tang Could you pull up some screen shots form Horizon to illustrate the steps of this procedure, please? If there is not a way in Horizon to do a step, maybe a sample command would be good. Thank you!

**Comment by LeslieLundquist** [comment]
@ying-tang I need to merge this as part of the release, but you can just open a new PR when you're ready. Thank you!

**Pull request merged**
