### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by JillTempelmeyer**
Add screenshots for Associate Floating IP, Floating IP Dialog Box, Allocate Floating IP

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer  Same comment as previous PR. Can we not have these images in our own repo?

**Comment by JillTempelmeyer** [comment]
@tw15egan Hey TJ! Would you mind looking at how I wrote the image URLs in the latest commit to this file for us? We want them to be hosted by our own internal repo, but able to be viewed externally on our customer-facing help docs site. Just want to make sure I'm structuring these correctly. Thank you in advance for any help/feedback you can provide! :)

**Comment by tw15egan** [comment]
@JillTempelmeyer you can reference any image in the `img` folder like so

`Associate Floating IP`

Let me know if you have any more problems!

**Comment by JillTempelmeyer** [comment]
@tw15egan Awesome! Thank you for your help!

**Comment by JillTempelmeyer** [comment]
One more question... I reformatted the images and now they're only showing up as links. Is there a way I can modify this to show the full picture within the doc? Thanks again!

**Comment by tw15egan** [comment]
@JillTempelmeyer are you running this locally or just hitting the preview button in Github? Since those are liquid tags, they won't show up until the changes are pushed (when it will be compiled by Jekyll)

**Comment by JillTempelmeyer** [comment]
Ah, that makes sense. I was just previewing the doc.

**Pull request merged**
