### PR TITLE
Add code block tags

### PR DESCRIPTION
**Pull request by ying-tang**
Add code block tags - This is a test.

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
Yes, this is how I have found to make the tags work. Jekyll needs the {bracketed} text, but Markdown needs the 

```
```

to display the block code properly, so I have been doing both. TJ says we should not need the 

```
```

but it does not display correctly without it, as far as I can see.

**Comment by LeslieLundquist** [comment]
wow, the empty gray spaces above represent the triple ticks of a code block, as you probably know.

**Comment by tw15egan** [comment]
I switched some things around and you should be able to use both the three back ticks or the syntax highlighting (just not both)

**Comment by LeslieLundquist** [comment]
Thanks! That is excellent, TJ!LESLIE D. LUNDQUIST
Director, Technical Content Development
IBM Blue Box Cloud
Phone: 1-206-607-0660
E-mail: llundquist@us.ibm.com-----TJ Egan notifications@github.com wrote: -----To: IBM-Blue-Box-Help/help-documentation help-documentation@noreply.github.comFrom: TJ Egan notifications@github.comDate: 05/04/2016 12:30PMCc: Leslie Lundquist/Seattle/IBM@IBMUS, State change state_change@noreply.github.comSubject: Re: [IBM-Blue-Box-Help/help-documentation] Add code block tags (#58)I switched some things around and you should be able to use both the three back ticks or the syntax highlighting (just not both)

**Pull request merged**
