### PR TITLE
Make sure there is no extra space in code blocks

### PR DESCRIPTION
**Pull request by ying-tang**
Make sure there is no extra space in code blocks, especially when {%highlight%} tags are used.

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
Wondering why you took out all of the numbered steps?

**Comment by LeslieLundquist** [comment]
Yes, Sophia, when I look at this document, I think the numbers you took out, in this case, actually need to be there, because the document is giving a step-by-step process in which the steps have to be executed in order. Also, other sections still do have numbers (correctly), so I wonder what made you decide to remove these particular ones? Let me also clarify something I wrote in a previous comment on another PR: I do not object to numbers such as 1, 2, 3, for a sequence of steps. What I do NOT want is that type of numbering that is 1.0, 1.1, 1.2, ...3.2, 3.3... and so forth, because it does not create the type of friendly documentation that I want us to produce. Thanks!

**Comment by ying-tang** [comment]
Hi Leslie, I like the sequence too. But in yesterday's [build result](http://ibm-blue-box-help.github.io/help-documentation/gettingstarted/commontech/Cloud_Images_Provided_by_IBM/) you could see the issues.
- There is extra space at the beginning of {%highlight%} code blocks in an ordered list, which is unfriendly to developers when they copy/paste, as you suggested. 
- Also, {%highlight%}  tags disturbs the ordered list. 

If we make {%highlight%} code blocks in an ordered list, like the following, 

```
1. Do something
   { %highlight bash% } 
   code
   code
   { %endhiglight%}
2. Do something else. 
```

Markdown will make this like the following after build:

```
1. Do something
(space) code
(space) code
1. Do something else. 
```

If we use the default markdown tag ``` for markdown, not the {highlight} tags, things would be better but there will be line break issues if the code block has multiple lines. Like:

```
1. Do something
   code  code
2. Do something else. 
```

So far I haven't find a good way of handling this issue. So removing the orders is just a mitigation. We could keep on working on this.

**Comment by LeslieLundquist** [comment]
@ying-tang If you use the default ``` tag for code blocks, it is ok to leave an extra blank line between each of the lines of code, so they do not concatenate into a single line, and they'll stay on separate lines.
Like this:

```
code

code

code
```

**Comment by ying-tang** [comment]
Thanks Leslie. Fixed all issues that appear with command blocks and sequences, and tested this file with local Jekyll.

**Pull request merged**
