### PR TITLE
Fix hyperlink and command syntax after local Jekyll test

### PR DESCRIPTION
**Pull request by ying-tang**
Fix hyperlink and command syntax after local Jekyll test

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@tw15egan could you take a look at this one, since it affects the gitignore file?

**Comment by ying-tang** [comment]
There is no change to the Gemfile.lock file but GitHub keeps reminding about the new line thing. I am not pretty sure if this is a problem. Please verify. Thanks!

**Comment by tw15egan** [comment]
@ying-tang & @LeslieLundquist I was able to pull the merged branch down and run it fine, so I don't see any problems with it. It looks like there were changes to the `.gitignore` file, but then they were removed. I found a few articles regarding whether or not the `Gemfile` and `Gemfile.lock` should not be included in the .gitignore file

> Assuming you're not writing a rubygem, Gemfile.lock should be in your repository. It's used as a snapshot of all your required gems and their dependencies. This way bundler doesn't have to recalculate all the gem dependencies each time you deploy, etc.

http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore

**Comment by LeslieLundquist** [comment]
@tw15egan Thanks!!

**Pull request merged**
