### PR TITLE
Add 0910 image release notes

### PR DESCRIPTION
**Pull request by ying-tang**
Add 09/10 image release notes prepared by the image team

### CODE REVIEW

**Comment by ying-tang** [comment]
@LeslieLundquist The image team got an agreement that the image releases will be loosely coupled with BBC releases. So adding these now won't be a big problem. 

The release date for images, i.e. 0910, reflects the date when the images are updated with the latest security fixes, so we'd better keep this date. 

@yangzhang-ibm @nirajdp76 @yiheqilin

**Comment by yangzhang-ibm** [comment]
Hi,
We got the following info from Niraj on Sep 9, so in short, we will keep `0910` date for image release version, but we should hold on this PR until 3.1.0 GA. Thanks to @ying-tang @LeslieLundquist and @nirajdp76 :

Hello
Even thou image release is loosely coupled with BlueBox release we will still be making new set of image go live for BlueBox on Oct14th aligning it with 3.1.0 release date. The image release can still have information based on when images were updated.i.e 0910. The refreshed images will be in test folder and not pushed to prod on objectstore until 3.1.0 GA.
Regards,
Niraj Patel

**Comment by LeslieLundquist** [comment]
Hi all, @nirajdp76 @yangzhang-ibm @ying-tang So We will hold off on merging this PR until 3.1.0 goes live. Got it. Thank you for making sure and letting me know.

**Comment by ying-tang** [comment]
@nirajdp76 @yangzhang-ibm @LeslieLundquist Hi all, guess it's time to merge this PR about image remote note?

**Comment by LeslieLundquist** [comment]
@ying-tang @yangzhang-ibm @nirajdp76 I was waiting until Friday, when 3.1.0 is scheduled to go live. If engineering prefers, I could merge it sooner.

**Pull request merged**
