### PR TITLE
Fix Nav Bar Link in BPUG

### PR DESCRIPTION
**Pull request by JillTempelmeyer**
Hey Leslie - it looks like there has been a nav bar image here, and the formatting: [See the Nav Bar] impacted its visibility. I've removed the wording so image can be viewed.

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer Oh, I see, but we can't use that image any more because it has the old Blue Box logo. I think you ought to try the new one, I don't remember that it had a deprecated logo.

**Comment by JillTempelmeyer** [comment]
@LeslieLundquist Ok, fixing it with the new one. I had that same thought, then noticed there are 2 existing images with the old Blue Box logo (dashboard and cloud images). Perhaps we should crop out the logo for these ones, too?

**Comment by LeslieLundquist** [comment]
@yikes, yes, please crop out any of the old logos in any images. Thanks!!

**Comment by LeslieLundquist** [comment]
@JillTempelmeyer yikes, yes, please crop out any of the old logos in any images. Thanks!!

**Comment by JillTempelmeyer** [comment]
@LeslieLundquist done.

**Pull request merged**
