### PR TITLE
Editorial updates to Cloud Images provided by IBM

### PR DESCRIPTION
**Pull request by ying-tang**
This pull request is majorly  for editorial changes.
The original author Yang Zhang and the editor Niraj will be invited to review and comment.

### CODE REVIEW

**Comment by ying-tang** [comment]
Inviting @nirajdp76 and @yangzhang-ibm to review and comment.

**Comment by yangzhang-ibm** [comment]
This change looks good to me. :+1:

**Comment by nirajdp76** [comment]
LGTM

**Comment by LeslieLundquist** [comment]
Line 50 -- we are using full pathnames. This link now may break soon. Please replace.

Lines 68 and 144 compare--either make the colon bold both places or not bold both places.

**Comment by LeslieLundquist** [comment]
Also line 232, double check, please.

**Comment by LeslieLundquist** [comment]
No punctuation at end of lines 126, 127 because they are effectively bulleted items, and they end with code commands, so it could be confusing

**Comment by LeslieLundquist** [comment]
Line 78, "dashboard" should be lowercase.

**Comment by LeslieLundquist** [comment]
Line 209 delete quotation marks.

**Comment by LeslieLundquist** [comment]
Line 174 should read:
You can upload an image either with ... or with ... .

(misplaced word "either" and non-parallel construction of noun clauses.)

**Comment by LeslieLundquist** [comment]
Line 176 insert the article "the" for "the OpenStack dashboard."

**Comment by LeslieLundquist** [comment]
Line 217, please insert "the," "an," or preferably the second-person possessive, "your," to make a complete sentence. Thanks!

**Comment by LeslieLundquist** [comment]
Line 334 looks as if it needs a link destination.

**Comment by LeslieLundquist** [comment]
Line 336 would be better starting with " To get support ....."

**Comment by LeslieLundquist** [comment]
Line 338, please delete the words "as follows," and add a short sentence at the end of the paragraph:

"Here's how:"

**Comment by LeslieLundquist** [comment]
Overall, this is very nice work! I especially like that you removed the numbering such as 3.1, 3.2, and so forth. I do not want to use that method of numbering in our documentation at all.

**Comment by LeslieLundquist** [comment]
I think the title "Working with cloud images provided by ...." is too long.
Could you please reset it **without**  "Working with" ?

Thank you for your good work!

**Comment by ying-tang** [comment]
@LeslieLundquist Thanks! Your comments were incorporated. Please further review.
The colon (:) after "Notes", we prefer not to bold for every occurrence.

**Comment by ying-tang** [comment]
Please also verify the added images, URLs, and the locations to put these images.Thank you.

**Comment by LeslieLundquist** [comment]
Why would you not want to use boldface colons consistently? I am really curious!

**Comment by LeslieLundquist** [comment]
Hi, Sophia, it looks as if your tables aren't displaying well, and I can't really check the figure links until the file is merged, or else they are not working, because I am getting 404 errors. I remember having trouble with the tables (and links) in the "Managing Users and Groups" document. I had to find a trick that I don't remember without going back to look, but what you can do is check that document and see that yours are formatted the same way.

**Comment by LeslieLundquist** [comment]
Otherwise, very good! This file is looking a lot better overall!

**Comment by ying-tang** [comment]
The colons: 
It was my personal misunderstanding about the IBM style guideline for technical information. The guideline also supports boldface colons in notes. I've made the changes globally. 

The tables:
The syntax seems to be in markups, not markdown. I guess this topic and the "managing users and projects" topics were, either imported from ICOS, or written by persons that previously worked with ICOS. ICOS adopted the markup approach, as you may know.  Anyway, I've changed these tables to markdown. 

The images:
You may not preview now as our paths to images are not relevant paths. 

The reference links:
I guess we should have a method of referring to another place (anchor), especially in the same document. This is not by default available in markdown, if I understand correctly, but very useful especially for long articles.

**Comment by tw15egan** [comment]
@ying-tang You can link to other parts of the page by wrapping the heading in paranthesis like so `(#first-section)`. 

Then when you are creating the table of contents at the beginning of the article, you can link to that heading like so: `[First Section](#first-section)`

[Here is a link for more info](https://gist.github.com/asabaylus/3071099)

Also, you can take a look at the README.md file at the root of the repo on how I did this for the 'Getting Started'

**Comment by LeslieLundquist** [comment]
Thanks, TJ!

**Pull request merged**
