### PR TITLE
Multiple page changes to hide 06/07 image release notes from top level (navigation, counts, lists)

### PR DESCRIPTION
**Pull request by ying-tang**
Multiple page setting changes to hide 06/07 image release notes from top level (navigation, counts, lists). Changes include:
- Common files such as _include/sidebar.html and _layout/page.html (this is to make sure the secondary file does not get counted in)
- Specific html files for userguides and getting started (make the file invisible)
- The .md file itself (change its featured attribute)

### CODE REVIEW

**Comment by ying-tang** [comment]
@LeslieLundquist and @yangzhang-ibm Please review. 

This change is to hide the 06/07 image release note (the secondary level file) so that it won't be displayed in lists or navigation and won't be counted.  

Frankly speaking this is a cumbersome way of implementing this change and is not so "scaleable" as we always expect. Fortunately this is only about appearance and won't impact other things. We could keep on improving the code.

**Comment by yangzhang-ibm** [comment]
Thanks to Ying for the help on this. Yes, the function of this change makes sense because we will have many image release notes for specific releases in the future, but we don't want to have all of them shown on the Getting Started home page. And I'd like to ask Leslie to review the code changes in this PR.

**Comment by LeslieLundquist** [comment]
Thanks, folks, for your help! @tw15egan this is more your area (for reviewing code changes), they look ok to me, but could you also give them a look?

**Comment by ying-tang** [comment]
@tw15egan Hi TJ, please take a review. The mechanism is very similar to what we have discussed about in [PR#144](https://github.com/IBM-Blue-Box-Help/help-documentation/pull/144). We used the "featured" field to judge whether this topic should be hidden from navigation and lists. 

The impacted files are sidebar, individual userguide and gettingstarted HTML pages, and common "pages".

**Comment by tw15egan** [comment]
@ying-tang @yangzhang-ibm @LeslieLundquist Pulled the changes in locally and they look good to me. If I add `hidden` to any topic under the User Guides section, they no longer show up in the nav bar, and are not counted. They still show up in search (which I assume is what we'd like?).

Nice work! 👍

**Comment by LeslieLundquist** [comment]
@ying-tang @yangzhang-ibm @tw15egan Thanks, everyone! I have been fully occupied these last few days with release and with education session, thanks for handling this so well! Our site is getting a lot of good attention right now!

**Pull request merged**
