### PR TITLE
Remove invalid password statement and add Heat autoscaling topic

### PR DESCRIPTION
**Pull request by ying-tang**
This request includes two things:
1) The Windows password statement is incorrect with Blue Box as it is based on the community version of OpenStack. No customization was done. The Windows password rule was customized only in ICOS. 
2) The Heat autoscaling feature mentioned in ICOS document has been tested and verified with Blue Box, so we imported this topic. 
Feel free to review and comment.

### CODE REVIEW

**Comment by LeslieLundquist** [comment]
I just verified yesterday with @omgjlk Jesse Keating and with Niraj @nirajdp76 that autoscaling is not working in our current 2.1.x release. As we move to Mitaka with our 3.0 release at the end of June, it will work in some fashion, but perhaps this document will not quite be accurate.

**Comment by LeslieLundquist** [comment]
As tedious as it may be, please let each Pull Request address only one topic.

**Comment by ying-tang** [comment]
So is there a special branch created for 3.0 that we could contribute drafts to? 
I will create another pull request for the Windows password thing.

**Comment by ying-tang** [comment]
Shall I close this pull request before working on another one?

**Comment by LeslieLundquist** [comment]
There is not currently a 3.0 branch for help docs. We just keep the gh-pages branch here for publishing--there is not even a master branch right now, because it is not needed, everything just goes right to published mode! That might be a good thing to do, though. I will check with TJ to see what he thinks and create the new branch if it is ok with him.

**Comment by LeslieLundquist** [comment]
@ying-tang  You could just make a new PR with the Windows change, if it is a small one. Then you could easily back that change out of this PR. I was thinking we could keep this PR here until we determine whether to go ahead and make a 3.0 branch. If you would rather close it, and make a new one later, that is OK with me!

**Comment by tw15egan** [comment]
@LeslieLundquist @ying-tang Creating more branches is definitely a good idea, as thats what I was doing when I made some changes to the UI, but if the branches are not merged often it could create a lot of merge conflicts. What we can look into doing is adding a YAML variable (such as weight, featured, etc..) like `draft` that will just not be shown on the website, and then can be removed when it is ready to be published

**Comment by LeslieLundquist** [comment]
Hey @tw15egan good suggestion! Actually we could probably use 2 YAML tags: draft and releaseTag.
That way, we could keep some drafts handy, such as that WIP Skeleton PR that I've had in there forever for the upcoming release notes, and also we'd have a way to associate documents with a particular release version from within the text file itself. I like that idea.

**Comment by tw15egan** [comment]
Actually, it looks like we can just create a `_drafts` folder, which would hide them from the site until they are ready, at which time they could simply be moved from the `_drafts` folder to their appropriate destination

https://jekyllrb.com/docs/drafts/

**Comment by LeslieLundquist** [comment]
It just gets better and better. If you can make it so, I will gladly commit my WIP skeleton release notes into drafts.

**Comment by tw15egan** [comment]
@LeslieLundquist Done. Now you can add `.md` files that you are working on to this folder, then when they are ready, move them to the correct folder so that WIP docs do not show up on the live site.

**Comment by ying-tang** [comment]
Thanks TJ and Leslie. This is very helpful. 
For this specific pull request, to avoid confusion I will close it and create another two, one for adding this new autoscaling topic into _draft and the other for the Windows password minor change.

**Pull request closed without merging**
